name: Checkmarx One Scan

# use only job-level permissions
permissions: {}

on:
  # pull_request_target allows secrets to be read from fork PRs.
  # DO NOT build or run checked out code from this job.
  #
  # Please note: Due to how this job is run, any changes to this
  # job will only take affect when merged to main.
  #
  # From https://michaelheap.com/access-secrets-from-forks/
  # Also see https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [ 'main' ]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read              # to query workflows/runs

    runs-on: ubuntu-latest

    steps:
      # TODO: Remove this checkout step once upload-sarif-github-action repo is made public
      # Currently required because GitHub Actions can't directly reference private repos
      - name: Checkout Upload action repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: midnightntwrk/upload-sarif-github-action
          ref: 8202d2182e4c0ebec293f9d9140c3378a2afe16e
          path: upload-sarif-github-action
          token: ${{ secrets.MIDNIGHTCI_REPO }}

      # Once public, can simplify to: uses: midnightntwrk/upload-sarif-github-action/checkmarx-scan@8202d2182e4c0ebec293f9d9140c3378a2afe16e
      - name: Checkmarx Full Scan
        uses: ./upload-sarif-github-action/checkmarx-scan
        with:
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
          scs-repo-token: ${{ secrets.MIDNIGHTCI_REPO }}
          upload-to-github: 'true'
          additional-params: " --branch ${{ github.event.pull_request.head.ref }} "
