name: Checkmarx One Scan (Fork-Friendly)

# use only job-level permissions
permissions: {}

on:
  pull_request_target:  # Changed from pull_request to pull_request_target
    types: [opened, synchronize, reopened]
    branches: [ '**' ]
  push:
    branches: [ 'main' ]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read              # to query workflows/runs

    runs-on: ubuntu-latest

    steps:
      # CRITICAL: DO NOT CHECKOUT THE PR CODE
      # This is what makes it safe with pull_request_target

      # TODO: Remove this checkout step once upload-sarif-github-action repo is made public
      # Currently required because GitHub Actions can't directly reference private repos
      - name: Checkout Upload action repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: midnightntwrk/upload-sarif-github-action
          ref: 02bb219118a8e40799065c9edd16175b77cd0d0d
          path: upload-sarif-github-action
          token: ${{ secrets.MIDNIGHTCI_REPO }}

      # Once public and merged, can simplify to:
      # uses: midnightntwrk/upload-sarif-github-action/checkmarx-scan-public@02bb219118a8e40799065c9edd16175b77cd0d0d
      - name: Checkmarx Full Scan (Fork-Friendly)
        uses: ./upload-sarif-github-action/checkmarx-scan-public
        with:
          project-name: midnightntwrk/midnight-node-docker
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
          # repo-url and branch are auto-detected from PR context
          upload-to-github: 'true'
